export enum GameState {
    MATCH_MAKING = "MATCH_MAKING",

    PICK_INITIAL_DESTINATION_CARDS = "PICK_INITIAL_DESTINATION_CARDS",

    TURN = "TURN",
    PICK_SECOND_TRAIN_CARD = "PICK_SECOND_TRAIN_CARD",
    PICK_DESTINATION_CARDS = "PICK_DESTINATION_CARDS",

    END = "END"
}