export enum PlayerAction {
    PICK_RANDOM_TRAIN_CARD = "PICK_RANDOM_TRAIN_CARD",
    PICK_TRAIN_CARD = "PICK_TRAIN_CARD",
    GET_DESTINATION_CARDS = "GET_DESTINATION_CARDS",
    PICK_DESTINATION_CARDS = "PICK_DESTINATION_CARDS",
    BUILD = "BUILD",

    JOIN_GAME = "JOIN_GAME",
    CREATE_GAME = "CREATE_GAME",
    START_GAME = "START_GAME",
}